image: debian/buster
environment:
  GITHUB_DELIVERY: 14eb7d04-7dce-11ea-9ece-ee773dea201e
  GITHUB_EVENT: push
  GITHUB_REF: refs/heads/master
  GITHUB_REPO: alexeldeib/az-local-pvc
  IMAGE: az-local-pvc
  REPO: docker.io/alexeldeib
packages:
- curl
- gpg
- apt-transport-https
repositories: null
secrets:
- 7bb48981-fc03-4344-bae3-736c99f94f49
- 21bdadaa-095c-4968-9a6e-ce9b795042b4
shell: null
sources:
- https://github.com/alexeldeib/bpf-demo
tasks:
- install: |
    ~/bpf-demo/build/setup_docker.sh
- build: |
    ~/bpf-demo/build/build.sh
- introspect: |
    lsblk